const heroes = [
  {
    id: 1,
    name: "Jonh",
    class: "warrior",
    level: 3,
    health: 20,
    power: 7,
    experience: 127,
    gold: 276,
    embarkedQuest: null,
  },
  {
    id: 2,
    name: "Steven",
    class: "wizard",
    level: 1,
    health: 5,
    power: 3,
    experience: 35,
    gold: 155,
    embarkedQuest: null,
  },
  {
    id: 3,
    name: "Flora",
    class: "wizard",
    level: 5,
    health: 25,
    power: 14,
    experience: 240,
    gold: 59,
    embarkedQuest: null,
  },
  {
    id: 4,
    name: "Ratta de curra",
    class: "warrior",
    level: 17,
    health: 95,
    power: 45,
    experience: 835,
    gold: 89,
    embarkedQuest: null,
  },
  {
    id: 5,
    name: "Currier",
    class: "warrior",
    level: 1,
    health: 10,
    power: 3,
    experience: 32,
    gold: 123,
    embarkedQuest: 6,
  },
  {
    id: 6,
    name: "Toster",
    class: "wizard",
    level: 1,
    health: 5,
    power: 4,
    experience: 28,
    gold: 5,
    embarkedQuest: 6,
  },
];

export default heroes;
