export enum ActionType {
  LOGOUT,

  FETCH_GAME_STATS_REQUEST,
  FETCH_GAME_STATS_SUCCESS,
  FETCH_QUESTS_REQUEST,
  FETCH_QUESTS_SUCCESS,
  FETCH_HEROES_REQUEST,
  FETCH_HEROES_SUCCESS,
  FETCH_BUILDINGS_REQUEST,
  FETCH_BUILDINGS_SUCCESS,
  FETCH_TAVERN_PATRONS_REQUEST,
  FETCH_TAVERN_PATRONS_SUCCESS,
  FETCH_MARKET_ASSORTMENT_REQUEST,
  FETCH_MARKET_ASSORTMENT_SUCCESS,
  FETCH_ALCHEMIST_ASSORTMENT_REQUEST,
  FETCH_ALCHEMIST_ASSORTMENT_SUCCESS,

  BUILDING_CLICKED,

  HERO_STATS_CHOOSED,
  HERO_STATS_DISPLAY_CLOSED,

  HEROES_EMBARKED_ON_QUEST,

  CHECKPOINT_PASSED,

  COMPLETE_QUEST,
  CANCEL_QUEST,

  SHOW_USER_MESSAGE,
  DISMISS_USER_MESSAGE,

  HERO_HIRED,
  HERO_DISMISSED,
  HERO_ACTIVITIES_UPDATED,

  SHOW_TOOLTIP,
  SHOW_CONFIRM_DIALOG,

  BEGIN_QUEST_PROCESS,
  CLOSE_QUEST_PROCESS,

  BUILDING_UPGRADE_STARTED,
  BUILDING_UPGRADE_COMPLETED,
}
